from typing import Any, Dict, List, Optional, Union, overload

from playwright.sync_api import (
    Browser,
    BrowserContext,
    Playwright,
    PlaywrightContextManager,
)
from typing_extensions import Literal

from foxyz.virtdisplay import VirtualDisplay

from .exceptions import InvalidProxy
from .utils import launch_options, sync_attach_vd



class Foxyz(PlaywrightContextManager):
    """
    Wrapper around playwright.sync_api.PlaywrightContextManager that automatically
    launches a browser and closes it when the context manager is exited.
    """

    def __init__(self, **launch_options):
        super().__init__()
        self.launch_options = launch_options
        self.browser: Optional[Union[Browser, BrowserContext]] = None

    def __enter__(self) -> Union[Browser, BrowserContext]:
        super().__enter__()
        try:
            self.browser = NewBrowser(self._playwright, **self.launch_options)
        except InvalidProxy as e:
            super().__exit__(InvalidProxy, e, None)
            raise
        return self.browser

    def __exit__(self, *args: Any):
        if self.browser:
            self.browser.close()
        super().__exit__(*args)


@overload
def NewBrowser(
    playwright: Playwright,
    *,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: Literal[False] = False,
    **kwargs,
) -> Browser: ...


@overload
def NewBrowser(
    playwright: Playwright,
    *,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: Literal[True],
    **kwargs,
) -> BrowserContext: ...


class _HeadfulBrowserWrapper:
    """
    Wraps a Playwright Browser to inject no_viewport=True into new_context()/new_page()
    calls so the content area follows OS window resize in headful mode.
    Delegates all other attribute access to the underlying browser.
    """

    def __init__(self, browser: Browser) -> None:
        self._browser = browser

    def new_context(self, **kwargs: Any) -> BrowserContext:
        kwargs.setdefault('no_viewport', True)
        ctx = self._browser.new_context(**kwargs)
        return ctx

    def new_page(self, **kwargs: Any):
        ctx = self.new_context()
        return ctx.new_page(**kwargs)

    def close(self, *args: Any, **kwargs: Any) -> None:
        return self._browser.close(*args, **kwargs)

    def __getattr__(self, name: str) -> Any:
        return getattr(self._browser, name)


def NewBrowser(
    playwright: Playwright,
    *,
    headless: Optional[Union[bool, Literal['virtual']]] = None,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: bool = False,
    debug: Optional[bool] = None,
    **kwargs,
) -> Union[Browser, BrowserContext]:
    """
    Launches a new browser instance for Foxyz given a set of launch options.

    Parameters:
        from_options (Dict[str, Any]):
            A set of launch options generated by `launch_options()` to use.
        persistent_context (bool):
            Whether to use a persistent context.
        **kwargs:
            All other keyword arguments passed to `launch_options()`.
    """
    if headless == 'virtual':
        virtual_display = VirtualDisplay(debug=debug)
        kwargs['virtual_display'] = virtual_display.get()
        headless = False
    else:
        virtual_display = None

    if not from_options:
        from_options = launch_options(headless=headless, debug=debug, **kwargs)

    # Persistent context
    if persistent_context:
        context = playwright.firefox.launch_persistent_context(**from_options)
        return sync_attach_vd(context, virtual_display)

    # Browser
    browser = playwright.firefox.launch(**from_options)
    browser = sync_attach_vd(browser, virtual_display)

    # In headful mode, wrap the browser so new_page()/new_context() apply
    # no_viewport=True by default, making the viewport follow OS window resize.
    if headless is False:
        browser = _HeadfulBrowserWrapper(browser)

    return browser
