import json as _json
import urllib.request
from typing import Any, Dict, List, Optional, Union, overload
from urllib.parse import urlparse

from playwright.sync_api import (
    Browser,
    BrowserContext,
    Playwright,
    PlaywrightContextManager,
)
from typing_extensions import Literal

from foxyz.virtdisplay import VirtualDisplay

from .exceptions import InvalidProxy
from .fingerprints import generate_context_fingerprint
from .utils import launch_options, sync_attach_vd


class Foxyz(PlaywrightContextManager):
    """
    Wrapper around playwright.sync_api.PlaywrightContextManager that automatically
    launches a browser and closes it when the context manager is exited.
    """

    def __init__(self, **launch_options):
        super().__init__()
        self.launch_options = launch_options
        self.browser: Optional[Union[Browser, BrowserContext]] = None

    def __enter__(self) -> Union[Browser, BrowserContext]:
        super().__enter__()
        try:
            self.browser = NewBrowser(self._playwright, **self.launch_options)
        except InvalidProxy as e:
            super().__exit__(InvalidProxy, e, None)
            raise
        return self.browser

    def __exit__(self, *args: Any):
        if self.browser:
            self.browser.close()
        super().__exit__(*args)


@overload
def NewBrowser(
    playwright: Playwright,
    *,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: Literal[False] = False,
    **kwargs,
) -> Browser: ...


@overload
def NewBrowser(
    playwright: Playwright,
    *,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: Literal[True],
    **kwargs,
) -> BrowserContext: ...


class _HeadfulBrowserWrapper:
    """
    Wraps a Playwright Browser to inject no_viewport=True into new_context()/new_page()
    calls so the content area follows OS window resize in headful mode.
    Delegates all other attribute access to the underlying browser.
    """

    def __init__(self, browser: Browser) -> None:
        self._browser = browser

    def new_context(self, **kwargs: Any) -> BrowserContext:
        kwargs.setdefault('no_viewport', True)
        ctx = self._browser.new_context(**kwargs)
        return ctx

    def new_page(self, **kwargs: Any):
        ctx = self.new_context()
        return ctx.new_page(**kwargs)

    def close(self, *args: Any, **kwargs: Any) -> None:
        return self._browser.close(*args, **kwargs)

    def __getattr__(self, name: str) -> Any:
        return getattr(self._browser, name)


def NewBrowser(
    playwright: Playwright,
    *,
    headless: Optional[Union[bool, Literal['virtual']]] = None,
    from_options: Optional[Dict[str, Any]] = None,
    persistent_context: bool = False,
    debug: Optional[bool] = None,
    **kwargs,
) -> Union[Browser, BrowserContext]:
    """
    Launches a new browser instance for Foxyz given a set of launch options.

    Parameters:
        from_options (Dict[str, Any]):
            A set of launch options generated by `launch_options()` to use
        persistent_context (bool):
            Whether to use a persistent context.
        **kwargs:
            All other keyword arugments passed to `launch_options()`.
    """
    if headless == 'virtual':
        virtual_display = VirtualDisplay(debug=debug)
        kwargs['virtual_display'] = virtual_display.get()
        headless = False
    else:
        virtual_display = None

    if not from_options:
        from_options = launch_options(headless=headless, debug=debug, **kwargs)

    # Persistent context
    if persistent_context:
        context = playwright.firefox.launch_persistent_context(**from_options)
        return sync_attach_vd(context, virtual_display)

    # Browser
    browser = playwright.firefox.launch(**from_options)
    browser = sync_attach_vd(browser, virtual_display)

    # In headful mode, wrap the browser so new_page()/new_context() apply
    # no_viewport=True by default, making the viewport follow OS window resize.
    if headless is False:
        browser = _HeadfulBrowserWrapper(browser)

    return browser


def _proxy_url_with_creds(proxy: Dict[str, str]) -> str:
    """Builds a proxy URL string with embedded credentials."""
    parsed = urlparse(proxy.get("server", ""))
    user = proxy.get("username", "")
    pwd = proxy.get("password", "")
    if user and pwd:
        return f"{parsed.scheme}://{user}:{pwd}@{parsed.netloc}"
    return proxy.get("server", "")


def _resolve_proxy_geo(proxy: Dict[str, str]) -> Dict[str, Optional[str]]:
    """Queries ip-api.com through the proxy for the exit IP and timezone."""
    proxy_url = _proxy_url_with_creds(proxy)
    handler = urllib.request.ProxyHandler({"http": proxy_url, "https": proxy_url})
    opener = urllib.request.build_opener(handler)
    try:
        with opener.open("http://ip-api.com/json?fields=query,timezone", timeout=10) as resp:
            data = _json.loads(resp.read())
            return {"ip": data.get("query") or None, "timezone": data.get("timezone") or None}
    except Exception:
        return {"ip": None, "timezone": None}


def NewContext(
    browser: Browser,
    *,
    preset: Optional[Dict[str, Any]] = None,
    os: Optional[str] = None,
    ff_version: Optional[str] = None,
    webrtc_ip: Optional[str] = None,
    proxy: Optional[Dict[str, str]] = None,
    geolocation: Optional[Dict[str, float]] = None,
    headless: Optional[bool] = None,
    **context_kwargs: Any,
) -> BrowserContext:
    """
    Creates a new browser context with a unique fingerprint identity.

    Each context gets its own real fingerprint preset
    with unique seeds for audio, canvas, and font spacing noise. All values are applied
    via addInitScript so they self-destruct before page scripts can detect them.

    Parameters:
        browser: A Browser instance from NewBrowser or Foxyz.
        preset: A specific fingerprint preset dict to use. If None, picks randomly.
        os: Target OS for preset selection ("windows", "macos", "linux").
        ff_version: Firefox version string for UA patching.
        webrtc_ip: IPv4 address to spoof for WebRTC ICE candidates.
        proxy: Per-context proxy (Playwright format: {"server": "...", "username": "...", "password": "..."}).
        geolocation: Per-context geolocation ({"latitude": float, "longitude": float}).
        headless: Whether the browser is running headless. When False, setScreenDimensions
            is skipped in the init script so the viewport follows actual OS window size.
        **context_kwargs: Additional Playwright new_context() options.
    """
    # Auto-derive WebRTC IP and timezone from proxy's exit IP when not explicitly provided
    if proxy and (not webrtc_ip or "timezone_id" not in context_kwargs):
        geo = _resolve_proxy_geo(proxy)
        if not webrtc_ip:
            webrtc_ip = geo["ip"]
        if "timezone_id" not in context_kwargs and geo["timezone"]:
            context_kwargs["timezone_id"] = geo["timezone"]

    fp = generate_context_fingerprint(preset=preset, os=os, ff_version=ff_version, webrtc_ip=webrtc_ip, headless=headless)

    # Merge generated context options with user overrides (user wins)
    opts: Dict[str, Any] = {**fp['context_options'], **context_kwargs}
    if proxy:
        opts['proxy'] = proxy
    if geolocation:
        opts['geolocation'] = geolocation
        opts.setdefault('permissions', ['geolocation'])

    context = browser.new_context(**opts)
    context.add_init_script(fp['init_script'])

    # Workaround: Playwright/Juggler treats dynamically-navigated iframes as
    # cross-origin, breaking javascript: URL iframes that fingerprint checkers
    # (e.g. pixelscan) use.  Inject a content-world script into HTML responses
    # that patches HTMLIFrameElement.prototype.src to convert javascript: URLs
    # into same-origin srcdoc iframes.
    _apply_jsurl_iframe_fix(context)

    return context
